export const install = resolve=>require(["./demo/install.vue"],resolve)
export const introduce = resolve=>require(["./demo/introduce.vue"],resolve)
export const HelloWorld = resolve=>require(["./demo/HelloWorld/index.vue"],resolve)
export const demoKeys = resolve=>require(["./demo/demoKeys/index.vue"],resolve)
export const demoTable = resolve=>require(["./demo/demoTable/index.vue"],resolve)
export const thanks = resolve=>require(["./demo/thanks.vue"],resolve)
